### ISSUE TITLE
Associativity of operators &&, ||, <, <=, >, >=

### ISSUE THREAD

**Issue by alextretyak** [douglascrockford/TDOP#4]
In the parse.js:
```
    infixr("&&", 30);
    infixr("||", 30);

    infixr("<", 40);
    infixr("<=", 40);
    infixr(">", 40);
    infixr(">=", 40);
```
Why `infixr` (and not just `infix`) is used there?

In JavaScript these operators [designated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence) as left-to-right associative.

**Comment by douglascrockford** [comment]
&& and || don't care because they short-circuit.

The comparison operators should not associate at all. a < b < c should be a syntax error.
