### ISSUE TITLE
The young and foolish times are over.

### ISSUE THREAD

**Issue by abulvenz** [douglascrockford/TDOP#6]
When browsing the code I found some comments, stating a certain youth and foolishness. Especially about "this" in the make_parse function.

Are there any plans to revise a new version, growing out of the cave of youth?

Following some talks about "the bad parts", it is true that the this code is not understandable for a humbled Java programmer who "did not bother to learn JavaScript". 

This issue can also be closed by redirecting to a source of learning that will help to understand the "itself" function.

**Comment by douglascrockford** [comment]
I wrote the original version of this code in 2001. If I were writing it today, I would not use 'this' as you suggest, taking a more functional approach. 

I have no plans to rewrite it.
